import os

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
VAULT_PARTIDAS = "/mnt/data/webdav/Obsidian/Obsidian/0300-Rol y Ocio 🎲/Partidas"

_FIELDS_DND5E = [
    {"key": "nombre",           "label": "Nombre",             "type": "text",   "required": True},
    {"key": "campaña",          "label": "Campaña",            "type": "text"},
    {"key": "jugador",          "label": "Jugador",            "type": "text"},
    {"key": "raza",             "label": "Raza",               "type": "text"},
    {"key": "clase",            "label": "Clase",              "type": "text"},
    {"key": "nivel",            "label": "Nivel",              "type": "number"},
    {"key": "hp_max",           "label": "PV Máx",             "type": "number"},
    {"key": "ca",               "label": "CA",                 "type": "number"},
    {"key": "bonus_iniciativa", "label": "Bonus Iniciativa",   "type": "number"},
    {"key": "fue", "label": "FUE", "type": "number", "group": "Atributos"},
    {"key": "des", "label": "DES", "type": "number", "group": "Atributos"},
    {"key": "con", "label": "CON", "type": "number", "group": "Atributos"},
    {"key": "int", "label": "INT", "type": "number", "group": "Atributos"},
    {"key": "sab", "label": "SAB", "type": "number", "group": "Atributos"},
    {"key": "car", "label": "CAR", "type": "number", "group": "Atributos"},
    {"key": "ataques", "label": "Ataques", "type": "textarea"},
    {"key": "notas",   "label": "Notas",   "type": "textarea"},
]

_FIELDS_ADND2E = [
    {"key": "nombre",  "label": "Nombre", "type": "text", "required": True},
    {"key": "campaña", "label": "Campaña", "type": "text"},
    {"key": "jugador", "label": "Jugador", "type": "text"},
    {"key": "raza",    "label": "Raza",   "type": "text"},
    {"key": "clase",   "label": "Clase",  "type": "text"},
    {"key": "nivel",   "label": "Nivel",  "type": "number"},
    {"key": "alineamiento", "label": "Alineamiento", "type": "select", "options": [
        "Legal Bueno", "Neutral Bueno", "Caótico Bueno",
        "Legal Neutral", "Neutral Puro", "Caótico Neutral",
        "Legal Malvado", "Neutral Malvado", "Caótico Malvado"]},
    {"key": "hp_max",  "label": "PG Máx", "type": "number"},
    {"key": "ca",      "label": "CA",     "type": "number"},
    {"key": "thac0",   "label": "GAC0",  "type": "number"},
    {"key": "experiencia", "label": "Experiencia (PX)", "type": "number"},
    {"key": "deidad", "label": "Deidad", "type": "text"},
    {"key": "altura", "label": "Altura", "type": "text"},
    {"key": "peso", "label": "Peso", "type": "text"},
    {"key": "edad", "label": "Edad", "type": "text"},
    {"key": "fue", "label": "FUE", "type": "number", "group": "Atributos"},
    {"key": "des", "label": "DES", "type": "number", "group": "Atributos"},
    {"key": "con", "label": "CON", "type": "number", "group": "Atributos"},
    {"key": "int", "label": "INT", "type": "number", "group": "Atributos"},
    {"key": "sab", "label": "SAB", "type": "number", "group": "Atributos"},
    {"key": "car", "label": "CAR", "type": "number", "group": "Atributos"},
    {"key": "st_muerte", "label": "Muerte/Veneno", "type": "number", "group": "Salvaciones"},
    {"key": "st_varita", "label": "Varita", "type": "number", "group": "Salvaciones"},
    {"key": "st_petrificacion", "label": "Petri./Polimorfia", "type": "number", "group": "Salvaciones"},
    {"key": "st_aliento", "label": "Aliento", "type": "number", "group": "Salvaciones"},
    {"key": "st_conjuros", "label": "Conjuros", "type": "number", "group": "Salvaciones"},
    {"key": "ataques", "label": "Ataques", "type": "textarea"},
    {"key": "pericias", "label": "Pericias (no armas)", "type": "textarea"},
    {"key": "pericias_armas", "label": "Pericias en armas", "type": "textarea"},
    {"key": "idiomas", "label": "Idiomas", "type": "textarea"},
    {"key": "conjuros", "label": "Conjuros", "type": "textarea"},
    {"key": "tesoro", "label": "Tesoro / Dinero", "type": "textarea"},
    {"key": "notas",   "label": "Notas",   "type": "textarea"},
]

_FIELDS_MOTHERSHIP = [
    {"key": "nombre",  "label": "Nombre",  "type": "text", "required": True},
    {"key": "campaña", "label": "Campaña", "type": "text"},
    {"key": "jugador", "label": "Jugador", "type": "text"},
    {"key": "clase",   "label": "Clase",   "type": "select",
     "options": ["Marine", "Teamster", "Científico", "Androide"]},
    {"key": "hp_max",     "label": "PV Máx",     "type": "number"},
    {"key": "estres_max", "label": "Estrés Máx", "type": "number"},
    {"key": "fuerza",       "label": "Fuerza",       "type": "number", "group": "Estadísticas"},
    {"key": "velocidad",    "label": "Velocidad",     "type": "number", "group": "Estadísticas"},
    {"key": "inteligencia", "label": "Inteligencia",  "type": "number", "group": "Estadísticas"},
    {"key": "combate",      "label": "Combate",       "type": "number", "group": "Estadísticas"},
    {"key": "ts_cordura",  "label": "Cordura",  "type": "number", "group": "Tiradas de salvación"},
    {"key": "ts_miedo",    "label": "Miedo",    "type": "number", "group": "Tiradas de salvación"},
    {"key": "ts_cuerpo",   "label": "Cuerpo",   "type": "number", "group": "Tiradas de salvación"},
    {"key": "ts_armadura", "label": "Armadura", "type": "number", "group": "Tiradas de salvación"},
    {"key": "ataques", "label": "Ataques", "type": "textarea"},
    {"key": "notas",   "label": "Notas",   "type": "textarea"},
]

_FIELDS_AGNOSTICO = [
    {"key": "nombre",  "label": "Nombre",  "type": "text", "required": True},
    {"key": "campaña", "label": "Campaña", "type": "text"},
    {"key": "jugador", "label": "Jugador", "type": "text"},
    {"key": "clase",   "label": "Clase",   "type": "text"},
    {"key": "nivel",   "label": "Nivel",   "type": "number"},
    {"key": "hp_max",  "label": "PV Máx",  "type": "number"},
    {"key": "ca",      "label": "CA",      "type": "number"},
    {"key": "ataques", "label": "Ataques", "type": "textarea"},
    {"key": "notas",   "label": "Notas",   "type": "textarea"},
]

SYSTEMS = {
    "dnd5e": {
        "id": "dnd5e",
        "name": "Dungeons & Dragons 5e",
        "short_name": "D&D 5e",
        "description": "El clásico juego de rol de fantasía épica.",
        "theme": "dnd5e",
        "icon": "🐉",
        "assistant_name": "Elminster",
        "assistant_icon": "🧙",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "dnd5e", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "dnd5e", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "dnd5e", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "dnd5e", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PV",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "DM Control Center",
        "character_types": ["player", "monster"],
        "rag_pdf_filter": "dnd5e",
        "has_encounter_gen": True,
        "player_fields": _FIELDS_DND5E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "D&D"),
    },
    "mothership": {
        "id": "mothership",
        "name": "Mothership RPG",
        "short_name": "Mothership",
        "description": "Supervivencia en el espacio exterior. Horror y ciencia ficción.",
        "theme": "mothership",
        "icon": "🛸",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "mothership", "npcs"),
            "spells":   os.path.join(BASE_DIR, "resources", "mothership", "equipment"),
            "rules":    os.path.join(BASE_DIR, "resources", "mothership", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "mothership", "players"),
        },
        "tab_labels": {
            "monsters": "NPCs",
            "spells":   "Equipo",
            "rules":    "Reglas",
        },
        "initiative_label": "VEL",
        "hp_label": "PV",
        "has_stress": True,
        "stress_label": "Estrés",
        "header_title": "MOTHERSHIP // WARDEN CONSOLE",
        "character_types": ["marine", "camionero", "cientifico", "androide", "criatura"],
        "rag_pdf_filter": "mothership",
        "assistant_name": "ARIA",
        "assistant_icon": "🤖",
        "player_fields": _FIELDS_MOTHERSHIP,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "Mothership"),
    },
    "adnd2e": {
        "id": "adnd2e",
        "name": "Advanced D&D 2ª Edición",
        "short_name": "AD&D 2e",
        "description": "La era dorada del rol. Reglas clásicas, bestiarios legendarios y mazmorreos sin cuartel.",
        "theme": "adnd2e",
        "icon": "📜",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "adnd2e", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "adnd2e", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "adnd2e", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "adnd2e", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PG",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "DUNGEON MASTER · AD&D 2ª Edición",
        "character_types": ["jugador", "monstruo"],
        "rag_pdf_filter": "adnd2e",
        "assistant_name": "Gygax",
        "assistant_icon": "📜",
        "player_fields": _FIELDS_ADND2E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "AD&D"),
    },
    "darksun": {
        "id": "darksun",
        "name": "Dark Sun — AD&D 2ª Edición",
        "short_name": "Dark Sun",
        "description": "Athas: un mundo postapocalíptico de arena, psiónica y supervivencia brutal.",
        "theme": "darksun",
        "icon": "☀️",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "darksun", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "darksun", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "darksun", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "darksun", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Psiónica",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PG",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "DUNGEON MASTER · DARK SUN",
        "character_types": ["jugador", "monstruo", "esclavo"],
        "rag_pdf_filter": "darksun",
        "assistant_name": "Boris",
        "assistant_icon": "☀️",
        "player_fields": _FIELDS_ADND2E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "AD&D", "Dark Sun"),
    },
    "ravenloft_adnd": {
        "id": "ravenloft_adnd",
        "name": "Ravenloft — AD&D 2ª Edición",
        "short_name": "Ravenloft AD&D",
        "description": "Las Tierras de Bruma originales. Horror gótico clásico con reglas de AD&D 2ª Edición.",
        "theme": "ravenloft",
        "icon": "🧛",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "ravenloft_adnd", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "ravenloft", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "ravenloft_adnd", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "ravenloft_adnd", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PG",
        "has_stress": False,
        "stress_label": "Terror",
        "header_title": "DUNGEON MASTER · RAVENLOFT AD&D",
        "character_types": ["jugador", "monstruo", "no-muerto", "villano"],
        "rag_pdf_filter": "adnd2e",
        "rag_source_filter": "Ravenloft",
        "assistant_name": "Van Richten",
        "assistant_icon": "🧛",
        "player_fields": _FIELDS_ADND2E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "AD&D"),
    },
    "ravenloft": {
        "id": "ravenloft",
        "name": "Ravenloft — D&D 5ª Edición",
        "short_name": "Ravenloft",
        "description": "Las Tierras de Bruma. Horror gótico, señores oscuros y terror sobrenatural.",
        "theme": "ravenloft",
        "icon": "🧛",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "ravenloft", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "ravenloft", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "ravenloft", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "ravenloft", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PV",
        "has_stress": False,
        "stress_label": "Terror",
        "header_title": "DUNGEON MASTER · RAVENLOFT",
        "character_types": ["jugador", "monstruo", "no-muerto", "villano"],
        "rag_pdf_filter": "dnd5e",
        "rag_source_filter": "Ravenloft",
        "assistant_name": "Van Richten",
        "assistant_icon": "🧛",
        "player_fields": _FIELDS_DND5E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "D&D"),
    },
    "greyhawk": {
        "id": "greyhawk",
        "name": "Greyhawk — AD&D 2ª Edición",
        "short_name": "Greyhawk",
        "description": "El Mundo del Pasado. Fantasía clásica en los Flanaess, cuna del rol.",
        "theme": "greyhawk",
        "icon": "🏰",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "greyhawk", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "greyhawk", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "greyhawk", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "greyhawk", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PG",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "DUNGEON MASTER · GREYHAWK",
        "character_types": ["jugador", "monstruo"],
        "rag_pdf_filter": "adnd2e",
        "rag_source_filter": "Greyhawk",
        "assistant_name": "Mordenkainen",
        "assistant_icon": "🏰",
        "player_fields": _FIELDS_ADND2E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "AD&D"),
    },
    "forgotten_realms": {
        "id": "forgotten_realms",
        "name": "Reinos Olvidados — AD&D 2ª Edición",
        "short_name": "Reinos Olvidados",
        "description": "Faerûn: los Reinos Olvidados en su época clásica. Magia arcana, aventura y grandeza.",
        "theme": "forgotten_realms",
        "icon": "⚔️",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "forgotten_realms", "monsters"),
            "spells":   os.path.join(BASE_DIR, "resources", "forgotten_realms", "spells"),
            "rules":    os.path.join(BASE_DIR, "resources", "forgotten_realms", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "forgotten_realms", "players"),
        },
        "tab_labels": {
            "monsters": "Bestiario",
            "spells":   "Conjuros",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PG",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "DUNGEON MASTER · REINOS OLVIDADOS",
        "character_types": ["jugador", "monstruo"],
        "rag_pdf_filter": "adnd2e",
        "rag_source_filter": "Forgotten Realms",
        "assistant_name": "Volo",
        "assistant_icon": "⚔️",
        "player_fields": _FIELDS_ADND2E,
        "vault_partidas_path": os.path.join(VAULT_PARTIDAS, "AD&D"),
    },
    "agnostico": {
        "id": "agnostico",
        "name": "Sistema Agnóstico",
        "short_name": "Agnóstico",
        "description": "Pantalla genérica para cualquier sistema de rol.",
        "theme": "agnostico",
        "icon": "🎲",
        "resources": {
            "monsters": os.path.join(BASE_DIR, "resources", "agnostico", "creatures"),
            "spells":   os.path.join(BASE_DIR, "resources", "agnostico", "skills"),
            "rules":    os.path.join(BASE_DIR, "resources", "agnostico", "rules"),
            "players":  os.path.join(BASE_DIR, "resources", "agnostico", "players"),
        },
        "tab_labels": {
            "monsters": "Criaturas",
            "spells":   "Habilidades",
            "rules":    "Reglas",
        },
        "initiative_label": "Ini",
        "hp_label": "PV",
        "has_stress": False,
        "stress_label": "Estrés",
        "header_title": "RPG Master Control",
        "character_types": ["jugador", "enemigo", "aliado"],
        "rag_pdf_filter": None,
        "assistant_name": "Oráculo",
        "assistant_icon": "🎲",
        "player_fields": _FIELDS_AGNOSTICO,
        "vault_partidas_path": VAULT_PARTIDAS,
    },
}

DEFAULT_SYSTEM = "dnd5e"


def get_system(system_id: str) -> dict:
    return SYSTEMS.get(system_id, SYSTEMS[DEFAULT_SYSTEM])


def get_all_systems() -> list[dict]:
    return list(SYSTEMS.values())
